//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneracionSecuencia
    {
        public int Id_Secuencia { get; set; }
        public int EmpleadoID { get; set; }
        public string SiglasDpto { get; set; }
        public string Destino { get; set; }
        public string Secuencia { get; set; }
        public System.DateTime Fecha_Incio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
    }
}
